resources:
- ../../kubernetes-1.15/pmem-csi-direct.yaml

commonLabels:
  pmem-csi.intel.com/deployment: direct-production

patchesJson6902:
- target:
    group: storage.k8s.io
    version: v1beta1
    kind: CSIDriver
    name: pmem-csi.intel.com
  path: ../patches/driverinfo-ephemeral-kubernetes-1-16-patch.yaml
