# Turns generic Kubernetes 1.14 deployment into deployment for LVM mode.

bases:
- ../kubernetes-1.14/

patchesJson6902:
- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: ../patches/lvm-patch.yaml
