# This JSON patch adds the  necessary annotation, port definitions and
# arguments to the PMEM-CSI node pod.

# PMEM-CSI:
- op: add
  path: /spec/template/metadata/annotations
  value:
    pmem-csi.intel.com/scrape: containers
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
  - name: metrics
    containerPort: 10010
- op: add
  path: /spec/template/spec/containers/0/command/-
  value: -metricsListen=:10010
- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    # If the PMEM-CSI driver is able to serve metrics,
    # then it is alive. In particular this covers capacity
    # checking.
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    # Allow it to fail 5 times. This is conservative
    # because the probe is new. It might get reduced
    # to 1 later.
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    # Startup may be slower when LVM needs to be set up first.
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

# TODO: node-driver-registrar once it has metrics support.

# external-provisioner:
- op: add
  path: /spec/template/metadata/annotations
  value:
    pmem-csi.intel.com/scrape: containers
- op: add
  path: /spec/template/spec/containers/2/ports
  value:
  - name: metrics
    containerPort: 10011
- op: add
  path: /spec/template/spec/containers/2/args/-
  value: --metrics-address=:10011
- op: add
  path: /spec/template/spec/containers/2/livenessProbe
  value:
    # If the provisioner is able to serve metrics,
    # then it is alive.
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    # Allow it to fail 5 times. This is conservative
    # because the probe is new. It might get reduced
    # to 1 later.
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/2/startupProbe
  value:
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    # The provisioner waits for the driver, so startup
    # may be slower when LVM needs to be set up first.
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
